function A_handle = linear_SBR6voltage_A(I_W_a,I_y,R_m,g,k_e,k_m,l,m_B,m_W,r)
%LINEAR_SBR6VOLTAGE_A
%    A_HANDLE = LINEAR_SBR6VOLTAGE_A(I_W_A,I_Y,R_M,G,K_E,K_M,L,M_B,M_W,R)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2020 07:48:55

t2 = l.^2;
t3 = r.^2;
t4 = I_W_a.*I_y.*2.0;
t5 = I_W_a.*m_B.*t2.*2.0;
t6 = I_y.*m_B.*t3;
t7 = I_y.*m_W.*t3.*2.0;
t8 = m_B.*m_W.*t2.*t3.*2.0;
t9 = t4+t5+t6+t7+t8;
t10 = 1.0./t9;
t11 = 1.0./R_m;
t12 = I_W_a.*2.0;
t13 = m_B.*t3;
t14 = m_W.*t3.*2.0;
t15 = l.*m_B.*r;
A_handle = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g.*m_B.^2.*t2.*t3.*t10,g.*l.*m_B.*t10.*(t12+t13+t14),0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,k_e.*k_m.*t10.*t11.*(I_y+t15+m_B.*t2).*-2.0,(k_e.*k_m.*t10.*t11.*(t12+t13+t14+t15).*2.0)./r,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,6]);
