function AA_handle = linear_SBRvoltage_A(I_W_a,I_W_d,I_y,I_z,R_m,d,g,k_e,k_m,l,m_B,m_W,n,r)
%LINEAR_SBRVOLTAGE_A
%    AA_HANDLE = LINEAR_SBRVOLTAGE_A(I_W_A,I_W_D,I_Y,I_Z,R_M,D,G,K_E,K_M,L,M_B,M_W,N,R)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-May-2020 14:52:00

t2 = l.^2;
t3 = r.^2;
t4 = I_W_a.*I_y.*2.0;
t5 = I_W_a.*m_B.*t2.*2.0;
t6 = I_y.*m_B.*t3;
t7 = I_y.*m_W.*t3.*2.0;
t8 = m_B.*m_W.*t2.*t3.*2.0;
t9 = t4+t5+t6+t7+t8;
t10 = 1.0./t9;
t11 = 1.0./R_m;
t12 = n.^2;
t13 = I_W_a.*2.0;
t14 = m_B.*t3;
t15 = m_W.*t3.*2.0;
t16 = l.*m_B.*r;
t17 = d.^2;
AA_handle = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g.*m_B.^2.*t2.*t3.*t10,g.*l.*m_B.*t10.*(t13+t14+t15),0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,k_e.*k_m.*t10.*t11.*t12.*(I_y+t16+m_B.*t2).*-2.0,(k_e.*k_m.*t10.*t11.*t12.*(t13+t14+t15+t16).*2.0)./r,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-(k_e.*k_m.*t11.*t12.*t17)./(I_W_d.*t3.*4.0+I_W_a.*t17+I_z.*t3.*2.0+m_W.*t3.*t17)],[6,6]);
